services:
  php:
    build:
      target: prod
    volumes: []

  worker:
    build:
      target: prod
    volumes: []

  nginx:
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    ports: []

  redis:
    ports: []

  rabbitmq:
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
