services:
  php:
    build:
      target: prod
    volumes: !reset []

  worker:
    build:
      target: prod
    volumes: !reset []

  nginx:
    ports: !reset []
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - proxy

  postgres:
    ports: []

  redis:
    ports: []

  rabbitmq:
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"

networks:
  proxy:
    external: true
